apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-node-express
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: simple-node-express
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/simple-node-express.git
